In [182]:
import numpy as np

In [183]:
arr_2d=np.array([[1,2,3],[4,5,6],[8,9,0]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [184]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [185]:
arr_2d[1:,:2]

array([[4, 5],
       [8, 9]])

In [186]:
arr=np.array([[1,2],['string'],[7,8]])
arr

array([list([1, 2]), list(['string']), list([7, 8])], dtype=object)

In [187]:
arr[1]

['string']

In [188]:
arr[0][1]

2

In [189]:
arr[0,0]

IndexError: too many indices for array

In [190]:
arr=np.arange(50).reshape(5,10)


In [191]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [192]:
# to get 33,34 values alone

arr[3,3:5]

array([33, 34])

In [193]:
arr.reshape(3,10)

ValueError: cannot reshape array of size 50 into shape (3,10)

In [194]:
a=np.ones(2)
a

array([ 1.,  1.])

In [195]:
b=np.zeros((2,4))
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [196]:
c=np.linspace(2,5,9)
c

array([ 2.   ,  2.375,  2.75 ,  3.125,  3.5  ,  3.875,  4.25 ,  4.625,  5.   ])

In [197]:
d=np.eye(6)
d

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [198]:
e=np.random.rand(0,1)
e

array([], shape=(0, 1), dtype=float64)

In [199]:
np.random.rand(5)

array([ 0.57887177,  0.07879857,  0.87399906,  0.56596327,  0.48683302])

In [200]:
g=np.random.rand(5,2)
g

array([[ 0.98344536,  0.72640207],
       [ 0.37246042,  0.9776168 ],
       [ 0.80710063,  0.49140076],
       [ 0.39760933,  0.84850469],
       [ 0.53538055,  0.20539648]])

In [201]:
np.random.randn(5)

array([-0.9521812 ,  2.25068162,  0.65620824, -1.13874781,  1.43362222])

In [202]:
np.random.randint(1,100,10)

array([33,  5,  6, 67, 40, 68, 67,  3, 77, 40])

In [203]:
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [204]:
h=g.reshape(2,5)
h

array([[ 0.98344536,  0.72640207,  0.37246042,  0.9776168 ,  0.80710063],
       [ 0.49140076,  0.39760933,  0.84850469,  0.53538055,  0.20539648]])

In [205]:
g.argmax()

0

In [206]:
g.argmin()

9

In [207]:
from numpy.random import randint

In [208]:
randint(8,10)

9

### Diff between list and numpy array

In [209]:
my_list=[1,2,3,4]
my_list[1:3]

[2, 3]

In [210]:
my_list[1:3]=100

TypeError: can only assign an iterable

In [211]:
my_lis=np.arange(1,10)
my_lis[1:3]
my_lis

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
my_lis[1:3]=100 #broad casting
my_lis

array([  1, 100, 100,   4,   5,   6,   7,   8,   9])

### Slicing effect

In [213]:
my_lis

array([  1, 100, 100,   4,   5,   6,   7,   8,   9])

In [214]:
my_lis1=my_lis[5:]
my_lis1

array([6, 7, 8, 9])

In [215]:
my_lis1[:]=2000

In [216]:
my_lis1

array([2000, 2000, 2000, 2000])

In [217]:
my_lis

array([   1,  100,  100,    4,    5, 2000, 2000, 2000, 2000])

### copy of array without reference

In [218]:
my_lis

array([   1,  100,  100,    4,    5, 2000, 2000, 2000, 2000])

In [219]:
my_lis_copy= my_lis.copy()
my_lis_copy
my_lis_copy[:]=555
my_lis_copy

array([555, 555, 555, 555, 555, 555, 555, 555, 555])

In [220]:
my_lis

array([   1,  100,  100,    4,    5, 2000, 2000, 2000, 2000])

### operations

In [221]:
arr=np.arange(10)

In [222]:
print(arr + arr)
print(arr-arr)
print(arr*arr)
print(arr/arr)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[ nan   1.   1.   1.   1.   1.   1.   1.   1.   1.]


C:\Users\margam\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [223]:
print(1/arr)

[        inf  1.          0.5         0.33333333  0.25        0.2
  0.16666667  0.14285714  0.125       0.11111111]


C:\Users\margam\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [224]:
arr.max()

9

In [225]:
arr-10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [226]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [227]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [228]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [229]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [248]:
from numpy.random import randint


In [288]:
arr=np.linspace(0.01,1,100).reshape(10,10)
arr

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])